jupyter-naas/drivers

- naas_drivers/__init__.py
- naas_drivers/gsheet.py
- tests/test_gsheet.py
Signed-off by: Navin Karkera <navin@disroot.org>
> fix(gsheet): fix google spreadsheet driver

- naas_drivers/inputOutput/thinkific.py
Update thinkific driver and dev low code formulas : users (create, delete, update, get), enrollments (create, update, get), course (get), group (create, get)
Canny: https://naas.canny.io/requests/p/thinkific-create-user
> feat(thinkific): refactor with api and use dataframe

- naas_drivers/inputOutput/gsheet.py
Adding a cancel and replace feature to the send method in order to clear the Sheet before sending data.
default behaviour is append through the new argument append with a default value : True.
if True: nothing changes
if False: clear the Sheet before sending (use of the delete API method see documentation)
It's my first PR please comment. I'll be glad to contribute.
> feat: add a cancel&replace feature when sending to gsheet

- .gitignore
- naas_drivers/__init__.py
- naas_drivers/output/streamlit.py
- setup.py
Hello, 
I have added a streamlit class that can be used as follows for any app:
```python
naas_driver.streamlit.run("app.py")
```
> feat: Run Streamlit apps from Naas server

- .gitignore
- naas_drivers/__init__.py
- naas_drivers/input/huggingface.py
- naas_drivers/input/nlp.py
- setup.py
Hello, 
I am planning to add the NLP pipeline that can be used as follows: 
```python
nlp= naas_drivers.nlp("text-generation")
nlp("Generate text")
```
> feat: HuggingFace NLP driver

- naas_drivers/__init__.py
- setup.py
Dependency's added and merged errors fixed
> fix: Adding dependencies 

- naas_drivers/input/emailbuilder.py
- Table header added
- Table border displayed
- Table fontsize fixed
> feat: emailbuilder improvement

- naas_drivers/__init__.py
> fix: Naas Drivers bug fixed

- naas_drivers/inputOutput/linkedin.py
> fix: change function name get posts stats from profile and get stats

- naas_drivers/input/newsapi.py
See this issue : https://github.com/jupyter-naas/awesome-notebooks/issues/148
> fix: newsapi fields problems

- naas_drivers/output/streamlit.py
> fix: Bug fix in streamlit driver

- naas_drivers/tools/notion.py
Hey, 
with @jravenel & @tparente-ui we have made a peer programming session to refactor the driver.
We also speak about the future fix and work we will need to do:
- `page.delete()` is currently not working 
- Updating properties is not available 
- We also need to develop the method inside the Database class in order to : 
-  delete a database
- create a new database
- retreive database field * awesome nootbook have been implemented: `get_database.ipynb`
> refactor: notion driver api

- naas_drivers/__init__.py
- naas_drivers/tools/zapier.py
See:  https://github.com/jupyter-naas/drivers/issues/164
Hi ! In this PR, the rename of the file and the class has been done.
> refactor: rename of the driver zappier -> zapier

- naas_drivers/tools/slack.py
See : https://github.com/jupyter-naas/drivers/issues/163
Hi ! In this PR, the line 43 of the driver have been removed like Jeremy said in the issue.
> fix: error in the driver

- naas_drivers/__init__.py
- naas_drivers/tools/naas_auth.py
- naas_drivers/tools/naas_credits.py
The goal of this pull request is to add first versions of `naas-auth` and `naas-credits` drivers.
> feat: Add naas-auth and naas-credits drivers.

- naas_drivers/tools/googleanalytics.py
A first version of the Google Analytics driver.
> feat: ga driver v0

- naas_drivers/__init__.py
- setup.py
The goal of this pull request is to load the drivers on call. This will make it possible to not have to install all the dependencies of naas_drivers if you only need to use only a subset of them.
> feat: Dynamic loading of drivers

- naas_drivers/tools/github.py
Hey @FlorentLvr !!
Referring to this issue #235,
Here is the driver code updated
Thanks!
> feat: github projects driver added

- naas_drivers/tools/github.py
Renamed a function name in the Projects class of Github driver.
Referring to this issue #235 
Thanks!
> fix: github get issues from projects

- naas_drivers/tools/email.py
> feat: new email methods

- naas_drivers/tools/streamlit.py
- setup.py
This pull request resolves https://github.com/jupyter-naas/awesome-notebooks/issues/1085
Removing ngrok usage
> fix(Streamlit): Remove ngrok and update streamlit version

- naas_drivers/__init__.py
- naas_drivers/tools/bigquery.py
@FlorentLvr Hey Florent, I just added the BigQuery driver. Could you please take a look and let me know if everything seems OK?
> feat: added the BigQuery driver

- .github/workflows/bump_version.yml
This pull requests resolves https://github.com/jupyter-naas/drivers/issues/358
> fix(CI): Bump commitizen-action
